// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7NYjYP-GdbBPEUxNQvOsy_KpKckfVphY',
    appId: '1:382499570970:web:c3ff1e07e5126b7ad698a3',
    messagingSenderId: '382499570970',
    projectId: 'tiktok-minchan',
    authDomain: 'tiktok-minchan.firebaseapp.com',
    storageBucket: 'tiktok-minchan.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdEZ2ibyyVze_5txKCf2hG9cxM4VvL65U',
    appId: '1:382499570970:android:74dd95fd32192c8bd698a3',
    messagingSenderId: '382499570970',
    projectId: 'tiktok-minchan',
    storageBucket: 'tiktok-minchan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz4hv0tnSuvhNdvymkJEgwYhn1r7lZj38',
    appId: '1:382499570970:ios:902bbfcdc7cd3ed0d698a3',
    messagingSenderId: '382499570970',
    projectId: 'tiktok-minchan',
    storageBucket: 'tiktok-minchan.firebasestorage.app',
    iosClientId: '382499570970-ieiivmnnpdtqfjdjdg3l9d4knde4qico.apps.googleusercontent.com',
    iosBundleId: 'com.minchan.tiktok',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7NYjYP-GdbBPEUxNQvOsy_KpKckfVphY',
    appId: '1:382499570970:web:99905d39fb67767dd698a3',
    messagingSenderId: '382499570970',
    projectId: 'tiktok-minchan',
    authDomain: 'tiktok-minchan.firebaseapp.com',
    storageBucket: 'tiktok-minchan.firebasestorage.app',
  );

}